(in-package :mu-cl-resources)

(defparameter *cache-count-queries* nil)
(defparameter *supply-cache-headers-p* t
  "when non-nil, cache headers are supplied.  this works together with mu-cache.")
;;(setf *cache-model-properties-p* t)
(defparameter *include-count-in-paginated-responses* t
  "when non-nil, all paginated listings will contain the number
   of responses in the result object's meta.")
(defparameter *max-group-sorted-properties* nil)

(read-domain-file "models/agenda.lisp")
(read-domain-file "models/agendapunt.lisp")
(read-domain-file "models/artikel.lisp")
(read-domain-file "models/behandeling-van-agendapunt.lisp")
(read-domain-file "models/besluitenlijst.lisp")
(read-domain-file "models/besluit.lisp")
(read-domain-file "models/bestuurseenheid-classificatie-code.lisp")
(read-domain-file "models/bestuurseenheid.lisp")
(read-domain-file "models/bestuursorgaan-classificatie-code.lisp")
(read-domain-file "models/bestuursorgaan.lisp")
(read-domain-file "models/blockchain-status.lisp")
(read-domain-file "models/concept.lisp")
(read-domain-file "models/concept-scheme.lisp")
(read-domain-file "models/notulen.lisp")
(read-domain-file "models/published-resource.lisp")
(read-domain-file "models/signed-resource.lisp")
(read-domain-file "models/stemming.lisp")
(read-domain-file "models/uittreksel.lisp")
(read-domain-file "models/versioned-agenda.lisp")
(read-domain-file "models/versioned-behandeling.lisp")
(read-domain-file "models/versioned-besluiten-lijst.lisp")
(read-domain-file "models/versioned-notulen.lisp")
(read-domain-file "models/werkingsgebied.lisp")
(read-domain-file "models/zitting.lisp")
