(define-resource published-resource ()
  :class (s-prefix "sign:PublishedResource")
  :properties `((:content :string ,(s-prefix "sign:text"))
                (:hash-value :string ,(s-prefix "sign:hashValue"))
                (:created-on :datetime ,(s-prefix "dct:created"))
                (:submission-status :uri ,(s-prefix "ext:submissionStatus")))
  :has-one `((blockchain-status :via ,(s-prefix "sign:status")
                                :as "status")
             (versioned-agenda :via ,(s-prefix "ext:publishesAgenda")
                               :as "versioned-agenda")
             (versioned-besluiten-lijst :via ,(s-prefix "ext:publishesBesluitenlijst")
                                        :as "versioned-besluiten-lijst")
             (versioned-behandeling :via ,(s-prefix "ext:publishesBehandeling")
                                        :as "versioned-behandeling")
             (versioned-notulen :via ,(s-prefix "ext:publiseshNotulen")
                                :as "versioned-notulen")
             (gebruiker :via ,(s-prefix "sign:signatory")
                        :as "gebruiker"))
  :resource-base (s-url "http://data.lblod.info/published-resources/")
  :features '(include-uri)
  :on-path "published-resources")