(define-resource stemming ()
  :class (s-prefix "besluit:Stemming")
  :properties `((:aantal-onthouders :number ,(s-prefix "besluit:aantalOnthouders"))
                (:aantal-tegenstanders :number ,(s-prefix "besluit:aantalTegenstanders"))
                (:aantal-voorstanders :number ,(s-prefix "besluit:aantalVoorstanders"))
                (:geheim :boolean ,(s-prefix "besluit:geheim"))
                (:title :string ,(s-prefix "dct:title"))
                (:gevolg :string ,(s-prefix "besluit:gevolg"))
                (:onderwerp :string ,(s-prefix "besluit:onderwerp")))
  :has-many `((mandataris :via ,(s-prefix "besluit:heeftAanwezige")
                          :as "aanwezigen")
              (mandataris :via ,(s-prefix "besluit:heeftOnthouder")
                          :as "onthouders")
              (mandataris :via ,(s-prefix "besluit:heeftStemmer")
                          :as "stemmers")
              (mandataris :via ,(s-prefix "besluit:heeftTegenstander")
                          :as "tegenstanders")
              (mandataris :via ,(s-prefix "besluit:heeftVoorstander")
                          :as "voorstanders"))
  :resource-base (s-url "http://data.lblod.info/id/stemmingen/")
  :features '(include-uri)
  :on-path "stemmingen")