;;TODO how to relate to superclass 'Agent' for heeftAanwezige
(define-resource zitting ()
  :class (s-prefix "besluit:Zitting")
  :properties `((:geplande-start :datetime ,(s-prefix "besluit:geplandeStart"))
                (:gestart-op-tijdstip :datetime ,(s-prefix "prov:startedAtTime"))
                (:geeindigd-op-tijdstip :datetime ,(s-prefix "prov:endedAtTime"))
                (:op-locatie :url ,(s-prefix "prov:atLocation")))

  :has-many `((mandataris :via ,(s-prefix "besluit:heeftAanwezigeBijStart")
                          :as "aanwezigen-bij-start")
              (agendapunt :via ,(s-prefix "besluit:behandelt")
                          :as "agendapunten")
              (uittreksel :via ,(s-prefix "ext:uittreksel")
                          :as "uittreksels")
              (agenda :via ,(s-prefix "ext:agenda")
                          :as "agendas"))

  :has-one `((bestuursorgaan :via ,(s-prefix "besluit:isGehoudenDoor")
                             :as "bestuursorgaan")
             (mandataris :via ,(s-prefix "besluit:heeftSecretaris")
                         :as "secretaris")
             (mandataris :via ,(s-prefix "besluit:heeftVoorzitter")
                         :as "voorzitter")
             (notulen :via ,(s-prefix "besluit:heeftNotulen")
                      :as "notulen")
             (besluitenlijst :via ,(s-prefix "ext:besluitenlijst")
                      :as "besluitenlijst"))
  :resource-base (s-url "http://data.lblod.info/id/zittingen/")
  :features '(include-uri)
  :on-path "zittingen")